name: flopyswf

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - flopy
  - python-dateutil>=2.4.0
  - affine
  - scipy
  - git
  - pandas
  - pyshp
  - rasterio
  - fiona
  - descartes
  - pyproj
  - shapely>=1.8
  - geos
  - geojson
  - vtk
  - rasterstats
  - pyvista
  - imageio
  - pymetis
  - trame
  - jupyter

  # pip installations
  - pip
  - pip:
      - git+https://github.com/MODFLOW-USGS/modflowapi.git